### ISSUE TITLE
A small error in Analysis_kidney.rmd vignette

### ISSUE THREAD

**Issue by martinfalck** [Siliegia/SIGMA#1]
Hi!

The line:
stress.genes <- intersect(stress.genes, rownames(expr.norm.log))

Should be: 
stress.genes <- intersect(s.genes, rownames(expr.norm.log))

Otherwise it will cause errors due do "exclude" having NaN values in the stress gene column since its s.genes that store stress genes.

**Comment by mariamircea** [comment]
Hi!
sorry for the confusion! "s.genes" are genes from the Seurat package associated with the S phase in the cell cycle. "stress.genes" are genes that have been found to be expressed due to the dissociation process, which I have included in this package: data("stress.genes"). The NaN values might be because I had saved the list of stress genes as factors and not as characters. I have now updated the list of stress genes to the character format. Let me know if it works!
